-- View: units_info_enriched
-- Target database: esa_pbi
-- Removed: unit_range, unit_type (replaced by label_* fields from unit_category_labels)

CREATE OR REPLACE VIEW units_info_enriched AS
 SELECT u."UnitID",
    u."SiteID",
    u."UnitTypeID",
    u."sLocationCode",
    u."sUnitName",
    u."sTypeName",
    u."sUnitNote",
    u."sUnitDesc",
    u."dcWidth",
    u."dcLength",
    u."iFloor",
    u."dcMapTheta",
    u."bMapReversWL",
    u."iEntryLoc",
    u."iDoorType",
    u."iADA",
        CASE
            WHEN u."SiteID" = ANY (ARRAY[2276, 24411, 25675, 29064, 33881, 39284, 40100]) THEN u."dcWidth" * u."dcLength" * 10.7639
            ELSE u."dcWidth" * u."dcLength"
        END AS dcarea_fixed,
    u."bClimate",
    u."bPower",
    u."bInside",
    u."bAlarm",
    u."bRentable",
    u."bMobile",
    u."bServiceRequired",
    u."bExcludeFromWebsite",
    u."bRented",
    u."bWaitingListReserved",
    u."bCorporate",
    u."iDaysVacant",
    u."iDaysRented",
    u."dMovedIn",
    u."iDefLeaseNum",
    u."DefaultCoverageID",
    u."dcStdRate",
    u."dcWebRate",
    u."dcPushRate",
    u."dcPushRate_NotRounded",
    u."dcBoardRate",
    u."dcPreferredRate",
    u."dcStdWeeklyRate",
    u."dcStdSecDep",
    u."dcRM_RoundTo",
    u."dcTax1Rate",
    u."dcTax2Rate",
    u."iPreferredChannelType",
    u."bPreferredIsPushRate",
    u.created_at,
    u.updated_at,
    cl.size_category AS label_size_category,
    cl.size_range AS label_size_range,
    cl.unit_type_code AS label_type_code,
    cl.climate_code AS label_climate_code,
    cl.shape AS label_shape,
    cl.pillar AS label_pillar,
    cl.final_label AS category_label,
    cl.published_at AS label_published_at,
    u.deleted_at,
    (u."SiteID"::text || '_'::text) || u."sUnitName"::text AS mimo_id
   FROM units_info u
     LEFT JOIN unit_category_labels cl ON cl.site_id = u."SiteID" AND cl.unit_id = u."UnitID";
